services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${PG_USER} -d ${PG_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
